metadata author = 'rwbr@outlook.de'
metadata repository = 'https://github.com/r-wbr/bicep-tools'

@description('Import library for location archetypes.')
import { location as locationType } from '../locations/shared.bicep'

@export()
func newPolicyDefinitionName(guidValue string) string => 'pd-${substring(guid(guidValue), 0, 18)}'

@export()
func newPolicyAssignmentName(guidValue string) string => 'pa-${substring(guid(guidValue), 0, 18)}'

@description('Creates a new role assignment based on choosen values.')
@export()
func newRoleAssignment(principalTypeValue principalType, roleValue roleDefinition, principalIdValue string) object => {
  name: guid(principalTypeValue, principalIdValue, roleValue)
  properties: setRoleAssignmentProperties(roleValue, principalIdValue, principalTypeValue)
}

@description('Selects the resource id for the role definitions using the role definition library.')
func getRoleResourceId(roleValue roleDefinition) string =>
  subscriptionResourceId('Microsoft.Authorization/roleDefinitions', loadYamlContent('library.yaml')[roleValue])

func setRoleAssignmentProperties(roleValue roleDefinition, principalId string, principalTypeValue principalType) roleAssignmentProperties => {
  roleDefinitionId: getRoleResourceId(roleValue)
  principalId: principalId
  principalType: principalTypeValue
}

@description('Defines available values for principal type.')
type principalType = 'Device' | 'ForeignGroup' | 'Group' | 'ServicePrincipal' | 'User'

@description('Defines the data type for reusable role assignment resources.')
type roleAssignmentProperties = resource<'Microsoft.Authorization/roleAssignments@2022-04-01'>.properties

@description('Defines available values for role definition.')
type roleDefinition =
  | 'AcrPush'
  | 'API Management Service Contributor'
  | 'AcrPull'
  | 'AcrImageSigner'
  | 'AcrDelete'
  | 'AcrQuarantineReader'
  | 'AcrQuarantineWriter'
  | 'API Management Service Operator Role'
  | 'API Management Service Reader Role'
  | 'Application Insights Component Contributor'
  | 'Application Insights Snapshot Debugger'
  | 'Attestation Reader'
  | 'Automation Job Operator'
  | 'Automation Runbook Operator'
  | 'Automation Operator'
  | 'Avere Contributor'
  | 'Avere Operator'
  | 'Azure Kubernetes Service Cluster Admin Role'
  | 'Azure Kubernetes Service Cluster User Role'
  | 'Azure Maps Data Reader'
  | 'Azure Stack Registration Owner'
  | 'Backup Contributor'
  | 'Billing Reader'
  | 'Backup Reader'
  | 'Blockchain Member Node Access (Preview)'
  | 'BizTalk Contributor'
  | 'CDN Endpoint Contributor'
  | 'CDN Profile Contributor'
  | 'CDN Profile Reader'
  | 'Classic Network Contributor'
  | 'Classic Storage Account Contributor'
  | 'Classic Storage Account Key Operator Service Role'
  | 'ClearDB MySQL DB Contributor'
  | 'Classic Virtual Machine Contributor'
  | 'Cognitive Services User'
  | 'Cognitive Services Data Reader (Preview)'
  | 'Cognitive Services Contributor'
  | 'CosmosBackupOperator'
  | 'Contributor'
  | 'Cosmos DB Account Reader Role'
  | 'Cost Management Contributor'
  | 'Cost Management Reader'
  | 'Data Box Contributor'
  | 'Data Box Reader'
  | 'Data Factory Contributor'
  | 'Data Purger'
  | 'Data Lake Analytics Developer'
  | 'DevTest Labs User'
  | 'DocumentDB Account Contributor'
  | 'DNS Zone Contributor'
  | 'EventGrid EventSubscription Contributor'
  | 'EventGrid EventSubscription Reader'
  | 'Graph Owner'
  | 'HDInsight Domain Services Contributor'
  | 'Intelligent Systems Account Contributor'
  | 'Key Vault Contributor'
  | 'Knowledge Consumer'
  | 'Lab Creator'
  | 'Log Analytics Reader'
  | 'Log Analytics Contributor'
  | 'Logic App Operator'
  | 'Logic App Contributor'
  | 'Managed Application Operator Role'
  | 'Managed Applications Reader'
  | 'Managed Identity Operator'
  | 'Managed Identity Contributor'
  | 'Management Group Contributor'
  | 'Management Group Reader'
  | 'Monitoring Reader'
  | 'Network Contributor'
  | 'New Relic APM Account Contributor'
  | 'Owner'
  | 'Reader'
  | 'Redis Cache Contributor'
  | 'Reader and Data Access'
  | 'Resource Policy Contributor'
  | 'Scheduler Job Collections Contributor'
  | 'Search Service Contributor'
  | 'Security Manager (Legacy)'
  | 'Security Reader'
  | 'Spatial Anchors Account Contributor'
  | 'Site Recovery Contributor'
  | 'Site Recovery Operator'
  | 'Spatial Anchors Account Reader'
  | 'Site Recovery Reader'
  | 'Spatial Anchors Account Owner'
  | 'SQL Managed Instance Contributor'
  | 'SQL DB Contributor'
  | 'SQL Security Manager'
  | 'Storage Account Contributor'
  | 'SQL Server Contributor'
  | 'Storage Account Key Operator Service Role'
  | 'Storage Blob Data Contributor'
  | 'Storage Blob Data Owner'
  | 'Storage Blob Data Reader'
  | 'Storage Queue Data Contributor'
  | 'Storage Queue Data Message Processor'
  | 'Storage Queue Data Message Sender'
  | 'Storage Queue Data Reader'
  | 'Support Request Contributor'
  | 'Traffic Manager Contributor'
  | 'User Access Administrator'
  | 'Virtual Machine Contributor'
  | 'Web Plan Contributor'
  | 'Website Contributor'
  | 'Azure Service Bus Data Owner'
  | 'Azure Event Hubs Data Owner'
  | 'Attestation Contributor'
  | 'HDInsight Cluster Operator'
  | 'Cosmos DB Operator'
  | 'Hybrid Server Resource Administrator'
  | 'Hybrid Server Onboarding'
  | 'Azure Event Hubs Data Receiver'
  | 'Azure Event Hubs Data Sender'
  | 'Azure Service Bus Data Receiver'
  | 'Azure Service Bus Data Sender'
  | 'Storage File Data SMB Share Reader'
  | 'Storage File Data SMB Share Contributor'
  | 'Private DNS Zone Contributor'
  | 'Storage Blob Delegator'
  | 'Desktop Virtualization User'
  | 'Storage File Data SMB Share Elevated Contributor'
  | 'Blueprint Contributor'
  | 'Blueprint Operator'
  | 'Microsoft Sentinel Contributor'
  | 'Microsoft Sentinel Responder'
  | 'Microsoft Sentinel Reader'
  | 'Policy Insights Data Writer (Preview)'
  | 'SignalR AccessKey Reader'
  | 'SignalR/Web PubSub Contributor'
  | 'Azure Connected Machine Onboarding'
  | 'Managed Services Registration assignment Delete Role'
  | 'App Configuration Data Owner'
  | 'App Configuration Data Reader'
  | 'Kubernetes Cluster - Azure Arc Onboarding'
  | 'Experimentation Contributor'
  | 'Cognitive Services QnA Maker Reader'
  | 'Cognitive Services QnA Maker Editor'
  | 'Experimentation Administrator'
  | 'Remote Rendering Administrator'
  | 'Remote Rendering Client'
  | 'Managed Application Contributor Role'
  | 'Security Assessment Contributor'
  | 'Tag Contributor'
  | 'Integration Service Environment Developer'
  | 'Integration Service Environment Contributor'
  | 'Azure Kubernetes Service Contributor Role'
  | 'Azure Digital Twins Data Reader'
  | 'Azure Digital Twins Data Owner'
  | 'Hierarchy Settings Administrator'
  | 'FHIR Data Contributor'
  | 'FHIR Data Exporter'
  | 'FHIR Data Reader'
  | 'FHIR Data Writer'
  | 'Experimentation Reader'
  | 'Object Understanding Account Owner'
  | 'Azure Maps Data Contributor'
  | 'Cognitive Services Custom Vision Contributor'
  | 'Cognitive Services Custom Vision Deployment'
  | 'Cognitive Services Custom Vision Labeler'
  | 'Cognitive Services Custom Vision Reader'
  | 'Cognitive Services Custom Vision Trainer'
  | 'Key Vault Administrator'
  | 'Key Vault Crypto User'
  | 'Key Vault Secrets Officer'
  | 'Key Vault Secrets User'
  | 'Key Vault Certificates Officer'
  | 'Key Vault Reader'
  | 'Key Vault Crypto Service Encryption User'
  | 'Azure Arc Kubernetes Viewer'
  | 'Azure Arc Kubernetes Writer'
  | 'Azure Arc Kubernetes Cluster Admin'
  | 'Azure Arc Kubernetes Admin'
  | 'Azure Kubernetes Service RBAC Cluster Admin'
  | 'Azure Kubernetes Service RBAC Admin'
  | 'Azure Kubernetes Service RBAC Reader'
  | 'Azure Kubernetes Service RBAC Writer'
  | 'Services Hub Operator'
  | 'Object Understanding Account Reader'
  | 'SignalR REST API Owner'
  | 'Collaborative Data Contributor'
  | 'Device Update Reader'
  | 'Device Update Administrator'
  | 'Device Update Content Administrator'
  | 'Device Update Content Reader'
  | 'Cognitive Services Metrics Advisor Administrator'
  | 'Cognitive Services Metrics Advisor User'
  | 'Schema Registry Reader (Preview)'
  | 'Schema Registry Contributor (Preview)'
  | 'AgFood Platform Service Reader'
  | 'AgFood Platform Service Contributor'
  | 'AgFood Platform Service Admin'
  | 'Managed HSM contributor'
  | 'Security Detonation Chamber Submitter'
  | 'SignalR REST API Reader'
  | 'SignalR Service Owner'
  | 'Reservation Purchaser'
  | 'AzureML Metrics Writer (preview)'
  | 'Storage Account Backup Contributor'
  | 'Experimentation Metric Contributor'
  | 'Project Babylon Data Curator'
  | 'Project Babylon Data Reader'
  | 'Project Babylon Data Source Administrator'
  | 'Application Group Contributor'
  | 'Desktop Virtualization Reader'
  | 'Desktop Virtualization Contributor'
  | 'Desktop Virtualization Workspace Contributor'
  | 'Desktop Virtualization User Session Operator'
  | 'Desktop Virtualization Session Host Operator'
  | 'Desktop Virtualization Host Pool Reader'
  | 'Desktop Virtualization Host Pool Contributor'
  | 'Desktop Virtualization Application Group Reader'
  | 'Desktop Virtualization Application Group Contributor'
  | 'Desktop Virtualization Workspace Reader'
  | 'Disk Backup Reader'
  | 'Disk Restore Operator'
  | 'Disk Snapshot Contributor'
  | 'Microsoft.Kubernetes connected cluster role'
  | 'Security Detonation Chamber Submission Manager'
  | 'Security Detonation Chamber Publisher'
  | 'Collaborative Runtime Operator'
  | 'CosmosRestoreOperator'
  | 'FHIR Data Converter'
  | 'Quota Request Operator'
  | 'EventGrid Contributor'
  | 'Security Detonation Chamber Reader'
  | 'Object Anchors Account Reader'
  | 'Object Anchors Account Owner'
  | 'WorkloadBuilder Migration Agent Role'
  | 'Azure Spring Cloud Data Reader'
  | 'Cognitive Services Speech Contributor'
  | 'Cognitive Services Face Recognizer'
  | 'Media Services Account Administrator'
  | 'Media Services Live Events Administrator'
  | 'Media Services Media Operator'
  | 'Media Services Policy Administrator'
  | 'Media Services Streaming Endpoints Administrator'
  | 'Stream Analytics Query Tester'
  | 'AnyBuild Builder'
  | 'IoT Hub Data Reader'
  | 'IoT Hub Twin Contributor'
  | 'IoT Hub Registry Contributor'
  | 'IoT Hub Data Contributor'
  | 'Test Base Reader'
  | 'Search Index Data Reader'
  | 'Search Index Data Contributor'
  | 'Storage Table Data Reader'
  | 'Storage Table Data Contributor'
  | 'DICOM Data Reader'
  | 'DICOM Data Owner'
  | 'EventGrid Data Sender'
  | 'Disk Pool Operator'
  | 'AzureML Data Scientist'
  | 'Grafana Admin'
  | 'Azure Connected SQL Server Onboarding'
  | 'Azure Relay Sender'
  | 'Azure Relay Owner'
  | 'Azure Relay Listener'
  | 'Grafana Viewer'
  | 'Grafana Editor'
  | 'Automation Contributor'
  | 'Kubernetes Extension Contributor'
  | 'Device Provisioning Service Data Reader'
  | 'Device Provisioning Service Data Contributor'
  | 'Trusted Signing Certificate Profile Signer'
  | 'Azure Spring Cloud Service Registry Reader'
  | 'Azure Spring Cloud Service Registry Contributor'
  | 'Azure Spring Cloud Config Server Reader'
  | 'Azure Spring Cloud Config Server Contributor'
  | 'Azure VM Managed identities restore Contributor'
  | 'Azure Maps Search and Render Data Reader'
  | 'Azure Maps Contributor'
  | 'Azure Arc VMware VM Contributor'
  | 'Azure Arc VMware Private Cloud User'
  | 'Azure Arc VMware Administrator role '
  | 'Cognitive Services LUIS Owner'
  | 'Cognitive Services Language Reader'
  | 'Cognitive Services Language Writer'
  | 'Cognitive Services Language Owner'
  | 'Cognitive Services LUIS Reader'
  | 'Cognitive Services LUIS Writer'
  | 'PlayFab Reader'
  | 'Load Test Contributor'
  | 'Load Test Owner'
  | 'PlayFab Contributor'
  | 'Load Test Reader'
  | 'Cognitive Services Immersive Reader User'
  | 'Lab Services Contributor'
  | 'Lab Services Reader'
  | 'Lab Assistant'
  | 'Lab Operator'
  | 'Lab Contributor'
  | 'Security Admin'
  | 'Web PubSub Service Owner'
  | 'Web PubSub Service Reader'
  | 'SignalR App Server'
  | 'Virtual Machine User Login'
  | 'Virtual Machine Administrator Login'
  | 'Azure Connected Machine Resource Administrator'
  | 'Backup Operator'
  | 'Workbook Contributor'
  | 'Workbook Reader'
  | 'Monitoring Contributor'
  | 'Monitoring Metrics Publisher'
  | 'Purview role 1 (Deprecated)'
  | 'Purview role 2 (Deprecated)'
  | 'Purview role 3 (Deprecated)'
  | 'Autonomous Development Platform Data Contributor (Preview)'
  | 'Autonomous Development Platform Data Owner (Preview)'
  | 'Autonomous Development Platform Data Reader (Preview)'
  | 'Key Vault Crypto Officer'
  | 'Device Update Deployments Reader'
  | 'Device Update Deployments Administrator'
  | 'Azure Arc VMware Private Clouds Onboarding'
  | 'Chamber Admin'
  | 'Microsoft Sentinel Automation Contributor'
  | 'CDN Endpoint Reader'
  | 'Chamber User'
  | 'Cognitive Services Speech User'
  | 'Windows Admin Center Administrator Login'
  | 'Azure Kubernetes Service Policy Add-on Deployment'
  | 'Guest Configuration Resource Contributor'
  | 'Domain Services Reader'
  | 'Domain Services Contributor'
  | 'DNS Resolver Contributor'
  | 'Azure Arc Enabled Kubernetes Cluster User Role'
  | 'Data Operator for Managed Disks'
  | 'AgFood Platform Sensor Partner Contributor'
  | 'Compute Gallery Sharing Admin'
  | 'Scheduled Patching Contributor'
  | 'DevCenter Dev Box User'
  | 'DevCenter Project Admin'
  | 'Virtual Machine Local User Login'
  | 'Azure Arc ScVmm VM Contributor'
  | 'Azure Arc ScVmm Administrator role'
  | 'Azure Arc ScVmm Private Clouds Onboarding'
  | 'Azure Arc ScVmm Private Cloud User'
  | 'HDInsight on AKS Cluster Pool Admin'
  | 'HDInsight on AKS Cluster Admin'
  | 'FHIR Data Importer'
  | 'API Management Developer Portal Content Editor'
  | 'VM Scanner Operator'
  | 'Elastic SAN Owner'
  | 'Elastic SAN Reader'
  | 'Desktop Virtualization Virtual Machine Contributor'
  | 'Desktop Virtualization Power On Off Contributor'
  | 'Desktop Virtualization Power On Contributor'
  | 'Elastic SAN Volume Group Owner'
  | 'Access Review Operator Service Role'
  | 'Trusted Signing Identity Verifier'
  | 'Video Indexer Restricted Viewer'
  | 'Monitoring Data Reader'
  | 'Azure Kubernetes Fleet Manager RBAC Writer'
  | 'Azure Kubernetes Fleet Manager RBAC Admin'
  | 'Azure Kubernetes Fleet Manager Contributor Role'
  | 'Azure Kubernetes Fleet Manager RBAC Reader'
  | 'Azure Kubernetes Fleet Manager RBAC Cluster Admin'
  | 'Kubernetes Namespace User'
  | 'Data Labeling - Labeler'
  | 'Role Based Access Control Administrator'
  | 'Template Spec Contributor'
  | 'Template Spec Reader'
  | 'Microsoft Sentinel Playbook Operator'
  | 'Deployment Environments User'
  | 'Azure Spring Apps Connect Role'
  | 'Azure Spring Apps Remote Debugging Role'
  | 'AzureML Registry User'
  | 'AzureML Compute Operator'
  | 'Azure Center for SAP solutions service role'
  | 'Azure Center for SAP solutions reader'
  | 'Azure Center for SAP solutions administrator'
  | 'AppGw for Containers Configuration Manager'
  | 'FHIR SMART User'
  | 'Cognitive Services OpenAI Contributor'
  | 'Cognitive Services OpenAI User'
  | 'Impact Reporter'
  | 'Impact Reader'
  | 'Azure Kubernetes Service Cluster Monitoring User'
  | 'ContainerApp Reader'
  | 'Azure Connected Machine Resource Manager'
  | 'SqlDb Migration Role'
  | 'Bayer Ag Powered Services GDU Solution'
  | 'Bayer Ag Powered Services Imagery Solution'
  | 'Azure Center for SAP solutions Service role for management'
  | 'Azure Center for SAP solutions Management role'
  | 'Kubernetes Agentless Operator'
  | 'Azure Usage Billing Data Sender'
  | 'SqlMI Migration Role'
  | 'Bayer Ag Powered Services CWUM Solution'
  | 'SqlVM Migration Role'
  | 'Azure Front Door Domain Contributor'
  | 'Azure Front Door Secret Reader'
  | 'Azure Front Door Secret Contributor'
  | 'Azure Front Door Domain Reader'
  | 'Azure Stack HCI Administrator'
  | 'MySQL Backup And Export Operator'
  | 'LocalNGFirewallAdministrator role'
  | 'LocalRulestacksAdministrator role'
  | 'Azure Extension for SQL Server Deployment'
  | 'Azure Maps Data Read and Batch Role'
  | 'API Management Service Workspace API Product Manager'
  | 'API Management Workspace API Developer'
  | 'API Management Workspace Reader'
  | 'API Management Workspace API Product Manager'
  | 'API Management Service Workspace API Developer'
  | 'API Management Workspace Contributor'
  | 'Storage File Data Privileged Reader'
  | 'Storage File Data Privileged Contributor'
  | 'Windows 365 Network User'
  | 'Windows365SubscriptionReader'
  | 'Windows 365 Network Interface Contributor'
  | 'App Compliance Automation Reader'
  | 'App Compliance Automation Administrator'
  | 'Azure Sphere Contributor'
  | 'SaaS Hub Contributor'
  | 'Azure Sphere Reader'
  | 'Azure Sphere Publisher'
  | 'Azure Machine Learning Workspace Connection Secrets Reader'
  | 'Procurement Contributor'
  | 'Cognitive Search Serverless Data Contributor (Deprecated)'
  | 'Cognitive Search Serverless Data Reader (Deprecated)'
  | 'Community Owner Role'
  | 'Firmware Analysis Admin'
  | 'Key Vault Data Access Administrator'
  | 'Defender for Storage Data Scanner'
  | 'Compute Diagnostics Role'
  | 'Elastic SAN Network Admin'
  | 'Cognitive Services Usages Reader'
  | 'PostgreSQL Flexible Server Long Term Retention Backup Role'
  | 'Search Parameter Manager'
  | 'Virtual Machine Data Access Administrator (preview)'
  | 'Logic Apps Standard Developer (Preview)'
  | 'Logic Apps Standard Contributor (Preview)'
  | 'Logic Apps Standard Operator (Preview)'
  | 'Logic Apps Standard Reader (Preview)'
  | 'IPAM Pool User'
  | 'SpatialMapsAccounts Account Owner'
  | 'Azure Resource Notifications System Topics Subscriber'
  | 'Elastic SAN Volume Importer'
  | 'Elastic SAN Snapshot Exporter'
  | 'Community Contributor Role'
  | 'EventGrid TopicSpaces Subscriber'
  | 'EventGrid TopicSpaces Publisher'
  | 'Data Boundary Tenant Administrator'
  | 'DeID Realtime Data User'
  | 'DeID Batch Data Reader'
  | 'DeID Batch Data Owner'
  | 'Carbon Optimization Reader'
  | 'Landing Zone Management Owner'
  | 'Landing Zone Management Reader'
  | 'Azure Stack HCI Device Management Role'
  | 'Azure Customer Lockbox Approver for Subscription'
  | 'Azure Resource Bridge Deployment Role'
  | 'Azure Stack HCI VM Reader'
  | 'Azure AI Developer'
  | 'Azure Stack HCI VM Contributor'
  | 'Deployment Environments Reader'
  | 'EventGrid Data Receiver'
  | 'EventGrid Data Contributor'
  | 'Advisor Reviews Contributor'
  | 'Advisor Reviews Reader'
  | 'Azure AI Inference Deployment Operator'
  | 'Connected Cluster Managed Identity CheckAccess Reader'
  | 'AgFood Platform Dataset Admin'
  | 'Defender for Storage Scanner Operator'
  | 'Azure Front Door Profile Reader'
  | 'Enclave Reader Role'
  | 'Azure Kubernetes Service Hybrid Cluster User Role'
  | 'Azure Kubernetes Service Hybrid Cluster Admin Role'
  | 'Azure Kubernetes Service Hybrid Contributor Role'
  | 'Enclave Owner Role'
  | 'Enclave Contributor Role'
  | 'Community Reader Role'
  | 'Storage Account Encryption Scope Contributor Role'
  | 'Operator Nexus Key Vault Writer Service Role (Preview)'
  | 'Key Vault Crypto Service Release User'
  | 'KubernetesRuntime Storage Class Contributor Role'
  | 'Azure Programmable Connectivity Gateway User'
  | 'Key Vault Certificate User'
  | 'Azure Spring Apps Managed Components Log Reader Role'
  | 'Azure Spring Apps Application Configuration Service Log Reader Role'
  | 'Azure Spring Apps Spring Cloud Gateway Log Reader Role'
  | 'Azure Edge On-Site Deployment Engineer'
  | 'Azure API Center Data Reader'
  | 'Azure impact-insight reader'
  | 'Defender Kubernetes Agent Operator'
  | 'Azure RedHat OpenShift Cloud Controller Manager Role'
  | 'Azure RedHat OpenShift Storage Operator Role'
  | 'Azure RedHat OpenShift Network Operator Role'
  | 'Azure RedHat OpenShift Image Registry Operator Role'
  | 'Azure RedHat OpenShift Azure Files Storage Operator Role'
  | 'Azure RedHat OpenShift Service Operator'
  | 'Azure RedHat OpenShift Machine API Operator Role'
  | 'Azure RedHat OpenShift Cluster Ingress Operator Role'
  | 'Azure Sphere Owner'
  | 'GroupQuota Request Operator'
  | 'GroupQuota Reader'
  | 'Bayer Ag Powered Services Smart Boundary Solution User Role'
  | 'Defender CSPM Storage Scanner Operator'
  | 'Advisor Recommendations Contributor (Assessments and Reviews)'
  | 'GeoCatalog Administrator'
  | 'GeoCatalog Reader'
  | 'Health Bot Editor'
  | 'Health Bot Reader'
  | 'Azure Programmable Connectivity Gateway Dataplane User'
  | 'Health Bot Admin'
  | 'Azure AI Enterprise Network Connection Approver'
  | 'Azure Container Storage Operator'
  | 'Azure Container Storage Contributor'
  | 'Azure Container Storage Owner'
  | 'Azure Kubernetes Service Arc Contributor Role'
  | 'Azure Kubernetes Service Arc Cluster User Role'
  | 'Azure Kubernetes Service Arc Cluster Admin Role'
  | 'Backup MUA Operator'
  | 'Backup MUA Admin'
  | 'Savings plan Purchaser'
  | 'CrossConnectionReader'
  | 'CrossConnectionManager'
  | 'Kubernetes Agent Operator'
  | 'Azure API Center Service Contributor'
  | 'Azure API Center Service Reader'
  | 'Azure API Center Compliance Manager'
  | 'Bayer Ag Powered Services Historical Weather Data Solution User Role'
  | 'Oracle.Database VmCluster Administrator Built-in Role'
  | 'Oracle.Database Reader Built-in Role'
  | 'Oracle.Database Owner Built-in Role'
  | 'Oracle Subscriptions Manager Built-in Role'
  | 'Oracle.Database Exadata Infrastructure Administrator Built-in Role'
  | 'Azure Messaging Catalog Data Owner'
  | 'Azure Spring Apps Application Configuration Service Config File Pattern Reader Role'
  | 'Azure Hybrid Database Administrator - Read Only Service Role'
  | 'Microsoft Sentinel Business Applications Agent Operator'
  | 'Azure ContainerApps Session Executor'
  | 'Azure Red Hat OpenShift Federated Credential Role'
  | 'Bayer Ag Powered Services Crop Id Solution User Role'
  | 'Scheduled Events Contributor'
  | 'Azure Spring Apps Job Execution Instance List Role'
  | 'Azure Spring Apps Job Log Reader Role'
  | 'Nexus Network Fabric Service Reader'
  | 'Nexus Network Fabric Service Writer'
  | 'Azure Deployment Stack Contributor'
  | 'Azure Deployment Stack Owner'
